// Builds the design-token pipeline.
//
// Reads the 3-tier DTCG token files (primitive -> semantic -> component),
// resolves all `{token.references}`, and emits a single typed, fully-resolved
// nested object to src/tokens/generated/tokens.ts for the MUI theme to consume.
//
// Run with: yarn build:tokens
import StyleDictionary from 'style-dictionary';

const GENERATED_HEADER =
	'// Do not edit directly — generated by Style Dictionary (`yarn build:tokens`).';

// Custom format: a fully-resolved, deeply-nested token tree as a typed const.
// Built from each token's `path`, so the output mirrors the authored structure.
StyleDictionary.registerFormat({
	name: 'typescript/nested-object',
	format: ({ dictionary }) => {
		const tree = {};

		dictionary.allTokens.forEach((token) => {
			const value = token.$value ?? token.value;
			let node = tree;
			token.path.forEach((segment, index) => {
				if (index === token.path.length - 1) {
					node[segment] = value;
				} else {
					node[segment] = node[segment] ?? {};
					node = node[segment];
				}
			});
		});

		return [
			GENERATED_HEADER,
			'',
			`export const tokens = ${JSON.stringify(tree, null, '\t')} as const;`,
			'',
			'export type Tokens = typeof tokens;',
			'',
			'export default tokens;',
			'',
		].join('\n');
	},
});

const sd = new StyleDictionary({
	source: ['src/tokens/{primitive,semantic,component}/**/*.json'],
	// Author tokens in the W3C Design Tokens (DTCG) `$value`/`$type` format.
	usesDtcg: true,
	platforms: {
		ts: {
			// `name/camel` only assigns unique per-token names (avoids collision
			// warnings); no value transforms run, so raw CSS values (hex,
			// `transparent`) pass through verbatim while references still resolve.
			transforms: ['name/camel'],
			buildPath: 'src/tokens/generated/',
			files: [
				{
					destination: 'tokens.ts',
					format: 'typescript/nested-object',
				},
			],
		},
	},
});

await sd.cleanAllPlatforms();
await sd.buildAllPlatforms();
